### ISSUE TITLE
Modèle DB

### ISSUE THREAD

**Issue by rudzboy** [vodkhard/vdk_inventory#2]
Salut, déjà merci pour ton script.
Ensuite comme beaucoup de gens j'ai eu l'erreur 1071 de SQL liée à la taille de l'index.

Voir : https://github.com/otland/forgottenserver/blob/master/schema.sql
Voir la table "player_items"

Faut pas utiliser le couple VARCHAR(255) + INT(11) comme PRIMARY KEY, ajouter un INT ici : "sid" en tant que KEY fera le boulot.

Faut gérer l'unicité du couple (player_id + item_id) certes.

Truc gratuit et facile : utilise un smallint pour ton identifiant items, sauf si t'as l'intention de créer plus d'1 million d'objets XD

A tester en urgence je pense.
Je peux pas tester pour toi, je bosse :wink: 

Bon courage, lâche pas le morceau ;)
PS: Tu l'as récupéré qq part le modèle ou fait à la main ? (simple curiosité :thinking:  )

**Comment by rudzboy** [comment]
Salut, pas de changements ?
Je suis curieux de voir comment ça peut marcher chez toi ? Quel est ton DB Engine ?
Mais sur InnoDB par exemple ça peut pas marcher.

Pourquoi avoir enlever la contrainte clé étrangère sur la table 'users' ?

**Comment by rudzboy** [comment]
Toujours là.

**Comment by rudzboy** [comment]
@vodkhard Je suis chiant d'insister je sais (mais je pense que ça vaut le coup) mais as-tu l'intention de le faire et/ou as-tu besoin d'aide ?

**Comment by vodkhard** [comment]
Salut j'avais pas vu ton message mais j'ai fait beaucoup de changements il me semble depuis ton premier message suite à des conseils qu'on m'a donné sur le forum ;)
